### ISSUE TITLE
unnecessary files

### ISSUE THREAD

**Issue by weinih** [chanvarma/proj4-eep153sp19-holbrook-working#3]
Couple files ".DS_Store", "Icon", "[EEP 153]Project 4 Notes_Goals - Holbrook Working.godc"
are not meaningful. 
Please add a necessary document to explain how them works.

**Comment by chanvarma** [comment]
Thanks for pointing this out. The error is fixed, and you can run the updated code by following the instructions under the 'Start here' section of the read-me linked below.

The "unnecessary" files were actually autocreated since we used a shared google drive as our github repository as well. Hope this helps!

[Read me](https://github.com/chanvarma/proj4-eep153sp19-holbrook-working/blob/master/README.md )
